version: 2

registries:
  grails-restricted:
    type: maven-repository
    url: https://repo.grails.org/grails/restricted

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    registries:
      - grails-restricted
